### ISSUE TITLE
Pull and push dry-run flag

### ISSUE THREAD

**Issue by galexrt** [ivanilves/lstags#111]
A pull (`-p`) dry run would show which images would be pulled.
A push (`-P`) dry run would show which images would a) be pulled and b) when the `-r` (external repo flag is given which images would be pushed to it.

This would allow for users to see issues like missing tags in a "plan" phase before running the actual pull/pull and push.

If this is wanted, depending on my time in the next weeks, I would be up to create a PR with this logic implemented.

**Comment by ivanilves** [comment]
Hi @galexrt

Yes, I think it is a great idea, it would give a major UX improvement for `lstags`! :+1:
