### ISSUE TITLE
feature: replace docker binary with img

### ISSUE THREAD

**Issue by Fsero** [ivanilves/lstags#118]
img provides an api compatible daemonless container builder and image fetcher, i think that it probably will improve CI build and test time and will make lstags more useful since it could be run without setting up a docker daemon :)

https://github.com/jessfraz/img

**Comment by ivanilves** [comment]
Great idea! I think we'll do it after we stabilize `v1` API.

**Comment by glensc** [comment]
there's no docker binary needed for lstags to operate afaik? it compiles with docker/cli?

**Comment by ivanilves** [comment]
The Docker binary is not needed for lstags to operate as long as, yes!, it has everything compiled inside. 

The Docker binary and service is in use in CI scripts only, and using `img` instead of Docker binary for build operations could save us up to ~30 seconds of CI run time,

**Comment by vonrabbe** [comment]
we use Docker daemon to run mock services for integration tests.

good idea, but we can't implement it because of this...
