### ISSUE TITLE
Sporadic CI `concurrent map write` failures

### ISSUE THREAD

**Issue by ivanilves** [ivanilves/lstags#143]
Last two months we started having sporadic CI `concurrent map write` failures.

We should monitor the situation and provide decisive fix on some point. Even though the rate is not critical for now, we should understand what **hard consequences** could bring us "half-working" CI in a long-term.

**Comment by ivanilves** [comment]
# UPDATE

:warning:  **This is a very serious error:** 
We need to hunt down all map writes we do in goroutines and replace them with channel writes.

**Comment by vonrabbe** [comment]
We do not have any concurrent map writes anymore!

After we merged https://github.com/ivanilves/lstags/pull/164 we got https://github.com/ivanilves/lstags/releases/tag/v1.0.69 we can be sure we are OK :muscle:
