### ISSUE TITLE
Registry API needs to be refactored

### ISSUE THREAD

**Issue by ivanilves** [ivanilves/lstags#149]
We need to implement abstract, well-tested API client for a registry:

#### It should:
* discover not only tags, but also image repositories
* be well covered by tests
* provide abstract interface to be easily extended, e.g. to add support of non-Docker registries

**Comment by ivanilves** [comment]
Started to work on this issue here: https://github.com/ivanilves/lstags/pull/166

**Comment by vonrabbe** [comment]
lets stop doing things for the greater good @ivanilves and start doing things requested by users 😉
