### ISSUE TITLE
Restore Pull/Push blackbox integration tests

### ISSUE THREAD

**Issue by ivanilves** [ivanilves/lstags#161]
We need to have some end2end blackbox integration tests to form the "last line" of defence before doing a release. A total "must have" before making stable automated releases https://github.com/ivanilves/lstags/issues/156 (we had these tests before, just need to examine git log and re-adopt them).

**Comment by vonrabbe** [comment]
after https://github.com/ivanilves/lstags/pull/164 got merged, can we close this issue?

**Comment by ivanilves** [comment]
YES!
