### ISSUE TITLE
quay.io registry gives only old tags

### ISSUE THREAD

**Issue by ivanilves** [ivanilves/lstags#188]
When we query a tag list for a repo hosted on`quay.io` - we get only old tags.

This is clearly on `quay.io` side, but they are not going to fix it. 

We need to either convince them to fix it, or add a workaround.

Thanks @pablocastellano for hitting on this important matter. 🙇

**Comment by nudgegoonies** [comment]
This is a duplicate of this one https://github.com/ivanilves/lstags/issues/185

**Comment by ivanilves** [comment]
oh shi- ! You are totally right!
