### ISSUE TITLE
Switch dependency tool from "dep" to "go mod"

### ISSUE THREAD

**Issue by zealic** [ivanilves/lstags#202]
I want contribute code for lstags, but lstags use dep, also go mod is offical dependencies management tool.

Please switch to "go mod". thanks.

See also:
https://blog.callr.tech/migrating-from-dep-to-go-1.11-modules/

**Comment by ivanilves** [comment]
Hey @zealic thanks for your interest and collaboration! 👏 

I've sent you a collaborator's invitation for this repository.

🤝
