### ISSUE TITLE
Quay.io 429 too many requests / slow performance

### ISSUE THREAD

**Issue by mattsimonsen** [ivanilves/lstags#204]
On an EC2 node, even with a concurrency set to one, quay.io is failing on a mirror with the following error:

Bad response status: 429 Too Many Requests >> https://quay.io/v2/jetstack/cert-manager-cainjector/tags/list?next_page=....

lstags -c 1 -r acctHere.dkr.ecr.us-east-2.amazonaws.com -f  lstags2.txt

An example config that fails consistently with Ubuntu 18.04, on EC2, is:

lstags:
  repositories:
    - quay.io/coreos/k8s-prometheus-adapter-amd64
    - quay.io/coreos/kube-rbac-proxy
    - quay.io/coreos/kube-state-metrics
    - quay.io/coreos/prometheus-config-reloader
    - quay.io/coreos/prometheus-operator
    - quay.io/jetstack/cert-manager-cainjector
    - quay.io/jetstack/cert-manager-controller
    - quay.io/jetstack/cert-manager-webhook

It would be helpful if a 429 induced additional delay, rather than exiting. It would be helpful to have the slowdown logged too.

On my workstation with same configuration, the processes completes, but seems to be far slower than expected (with little network IO).

Thanks
Matt

**Comment by ivanilves** [comment]
Great tip @mattsimonsen

**Comment by vonrabbe** [comment]
@mattsimonsen I've tested your setup with new lstags https://github.com/ivanilves/lstags/releases/tag/v1.2.11 and now it works as expected. I'm closing the issue. Feel free to comment or reopen!

**Comment by ivanilves** [comment]
Thank you for code review and for testing @vonrabbe 🙏
