### ISSUE TITLE
Use PushTemplate to change remote push path

### ISSUE THREAD

**Issue by zealic** [ivanilves/lstags#205]
In some scenarios, the local and remote registry paths may be different, and we need some way to change this path.
The reference implementation here is to use the go template + [sprig](http://masterminds.github.io/sprig/) functions to support this feature.

Example:
```
lstags -f ../images-product.yml \
  -R product-prd --push-path-template="{{ .Prefix}}{{ .Path | base }}" \
  -U -r registry.example.com
```

**Comment by ivanilves** [comment]
Hey @zealic now specs are fixed: https://github.com/ivanilves/lstags/pull/208

Could you or @vonrabbe review this, so we can merge it and get an automatic release? 🙏
