### ISSUE TITLE
Unauthorized on gcr.io

### ISSUE THREAD

**Issue by fredbi** [ivanilves/lstags#211]
Trying to use lstag (CLI and lib) against private repo hosted on gcr.io.
`lstags` cannot connect to the repo (but the corresponding `docker pull ...` works).

After some quick analysis looks like:
- the credentials helper part works well and is able to grab a fresh token from the gcr helper
- the API should use the bearer token here and not `username`/`password`.

**Comment by ivanilves** [comment]
Hi @fredbi thanks for opening this issue!

This could be interesting to debug 👌 

Meanwhile, could you please try to use "JSON key file" authentication for GCR:

Described here: https://cloud.google.com/container-registry/docs/advanced-authentication 

This may provide you a quick workaround 😉

**Comment by fredbi** [comment]
Thank you so much @ivanilves -- yeah that would typically with a service account, e.g. CI.
I am giving the source base a more in-depth read and try to figure it out. Kudos for this tool which IMHO should definitely be a part of docker distros.

**Comment by ivanilves** [comment]
Thank you for these warm words!

I'm just trying to do something with the very little time I have 😅

**Comment by ivanilves** [comment]
Closing - as "JSON key file" method works pretty fine :slightly_smiling_face: 

Feel free to re-open and collaborate on this feature if interested.
