### ISSUE TITLE
Create missing repositories

### ISSUE THREAD

**Issue by cablespaghetti** [ivanilves/lstags#223]
I would be really great if this tool had the ability to create missing repositories, in our case this would require integrating with the ECR API. Currently I have to do this manually for each new repository I add to the configuration.

**Comment by ivanilves** [comment]
Sounds like a good idea. Thanks @cablespaghetti !

**Comment by ivanilves** [comment]
Closing. Reason: No time to implement it :slightly_smiling_face: 

Feel free to re-open and collaborate on this!
