### ISSUE TITLE
Package tests

### ISSUE THREAD

**Issue by vonrabbe** [ivanilves/lstags#24]
We have main.go tested but what about packages?

Could we also have some testing for packages?

**Comment by ivanilves** [comment]
Yes, this is pretty important...

**Comment by ivanilves** [comment]
Here are some potentially useful links:

* https://golang.org/pkg/net/http/httptest/
* https://github.com/h2non/gock
* https://github.com/jarcoal/httpmock

**Comment by ivanilves** [comment]
Lowered priority. Testing for testing is not so cool when you need features...

**Comment by ivanilves** [comment]
The tests are added ... but only into placed we really need. This issue should be closed!
