### ISSUE TITLE
Support Insecure docker registries

### ISSUE THREAD

**Issue by msoedov** [ivanilves/lstags#56]
```shell
lstags private-host/cassandra
Get https://private-host/v2: http: server gave HTTP response to HTTPS client
```

**Comment by ivanilves** [comment]
Thanks for opening this @msoedov !

Agree, we need to add something like `--insecure` feature flag ASAP.

**Comment by ivanilves** [comment]
https://github.com/ivanilves/lstags/pull/58

**Comment by vonrabbe** [comment]
https://github.com/ivanilves/lstags/releases/tag/v10 @msoedov try if it solves your issue :wink:

**Comment by msoedov** [comment]
@ivanilves @vonrabbe  Thanks for the patch. I will try tomorrow.

**Comment by msoedov** [comment]
You don't support v1 registry right?

```shell
lstags -i private-registry:9000/p/cassandra
Bad response status: 500 INTERNAL SERVER ERROR >> http://private-registry:9000/v2/p/cassandra/tags/list
```

**Comment by ivanilves** [comment]
@msoedov I fear we do not. :cry: 

We never considered supporting `v1` cause `v2` is now [almost] everywhere.

Just curios: Why do you use `v1` registry?

**Comment by msoedov** [comment]
@ivanilves  Part of a legacy system

**Comment by ivanilves** [comment]
I got it @msoedov :disappointed: 

This happens.

**Comment by ivanilves** [comment]
I think we may close that issue?

**Comment by msoedov** [comment]
Thanks guys

**Comment by ivanilves** [comment]
You are welcome!
