### ISSUE TITLE
Problem with private registry with port number

### ISSUE THREAD

**Issue by huajunzeng** [ivanilves/lstags#68]
Hi, It's a very useful tool. However I found a mismatch problem when our private registry is hosted on a port e.g. 5000. An example as below.

```
$ docker images
my.registry.com:5000/my_image                 my_tag          abfaa2fbade0        10 months ago       97MB

$ lstags my.registry.com:5000/my_image
<STATE>      <DIGEST>                                      <(local) ID>    <Created At>              <TAG>
LOCAL-ONLY   sha256:85b750cd33aa29ffce453f63984f4f6c9      abfaa2fbade0    2016-11-30T03:37:55-08:00 my.registry.com:5000/my_image:5000/my_image
ABSENT       sha256:85b750cd33aa29ffce453f63984f4f6c9      n/a             2016-11-30T03:37:55-08:00 my.registry.com:5000/my_image:my_tag

```

It seems the colon before the port number caused the wrong parsing result somewhere.

Thanks!

**Comment by ivanilves** [comment]
@huajunzeng thank you for reporting it!

You are right. *We know we need to write more tests to avoid things like this and we are writing em now* :wink: 

Fixed here: https://github.com/ivanilves/lstags/pull/69

Download here: https://github.com/ivanilves/lstags/releases/tag/v15

**Comment by ivanilves** [comment]
As long as fix was already tested and released, closing the issue! :muscle: :wink:
