### ISSUE TITLE
"norelease" branches

### ISSUE THREAD

**Issue by vonrabbe** [ivanilves/lstags#76]
IMO we need some mechanism to show that the PR we merge should not create a release.

For example, a refactor PR, which should be tested as any other PR, but should not be released cause it provides no value for user.

**Comment by ivanilves** [comment]
Good idea but for the time being I would like to release everything :wink:

**Comment by ivanilves** [comment]
https://github.com/ivanilves/lstags/pull/96 OK we've done it!
