### ISSUE TITLE
Docker pull/push does not retry on failure

### ISSUE THREAD

**Issue by ivanilves** [ivanilves/lstags#84]

**Comment by vonrabbe** [comment]
This is not critical IMO, unlike registry queries pulls and pushes are pretty reliable.

We'd better go for this https://github.com/ivanilves/lstags/issues/93

**Comment by ivanilves** [comment]
Solved this! This does not cover pushes. I think if push-registry is assumed local, we do not need push retries!

**Comment by vonrabbe** [comment]
merged but you will regret not including push retries IMO

you lazy son of a ...
