### ISSUE TITLE
index out of range error

### ISSUE THREAD

**Issue by ryanking** [ivanilves/lstags#87]
Just trying to get things up and running–

```
$ lstags --version
VERSION: v30-d15b77b
$ lstags alpine~/^3\\./
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/ivanilves/lstags/docker/config.Load(0x1360289, 0x15, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/ivanilves/lstags/docker/config/config.go:79 +0x4fe
main.main()
	/home/travis/gopath/src/github.com/ivanilves/lstags/main.go:98 +0x8d
```

**Comment by ivanilves** [comment]
Hello @ryanking 

It fails to load `~/.docker/config.json` (looks like it exists but some strange thing happens on the load).
Could you please show me your `~/.docker/config.json` ? (NB! You need to delete/obscurify alls the "auth" fields)

**Comment by edkellena** [comment]
@ivanilves I also have this straight after installing (from release binary).
My redacted `~/.docker/config.json` is:
```
╰─ cat ~/.docker/config.json
{
	"auths": {
		"xxxxx.dkr.ecr.us-east-1.amazonaws.com": {},
		"https://xxxxx.dkr.ecr.us-east-1.amazonaws.com": {},
		"https://index.docker.io/v1/": {}
	},
	"HttpHeaders": {
		"User-Agent": "Docker-Client/17.09.0-ce (darwin)"
	},
	"credsStore": "osxkeychain"
}%
```

**Comment by ivanilves** [comment]
Hey @vonrabbe why did you close it?

**Comment by vonrabbe** [comment]
Sorry... new keyboard...

**Comment by vonrabbe** [comment]
Hey @ryanking :wave: 

Please grab the new release:
https://github.com/ivanilves/lstags/releases/tag/v31

@ivanilves made an automated test, I've made a manual one, config should be loaded fine now. :ok_hand:

**Comment by ryanking** [comment]
@vonrabbe new version works

**Comment by ivanilves** [comment]
Great! Thanks @ryanking Thanks @vonrabbe
