### ISSUE TITLE
yaml file support

### ISSUE THREAD

**Issue by vonrabbe** [ivanilves/lstags#89]
we need to support configuration loading from yaml file as it is more scm/git friendly

**Comment by ivanilves** [comment]
Definitely a good idea! I was thinking about this also.

**Comment by ivanilves** [comment]
https://github.com/ivanilves/lstags/pull/136

**Comment by vonrabbe** [comment]
Great! I would like to merge it if no objections during next couple of days

**Comment by ivanilves** [comment]
This is DONE!
